#!/bin/bash

bold=`tput bold`
normal=`tput sgr0`

echo "*******************************"
echo "Linux Lite - Disable Auto Login"
echo "*******************************"
echo ""
echo "This will disable auto login for your computer."
echo "This will ${bold}ONLY${normal} work for the current login manager."
echo "If you install another login manager, this feature will not work."
echo ""
echo "Please enter your password to continue..."
sudo sed -i "s/autologin-user=$USER/autologin-user=linux/g" /etc/lightdm/lightdm.conf
echo "Auto login is now disabled."
echo "Next time you reboot your computer, you will"
echo "login with your usual username and password."
echo "Press any Key to close this window."
read -n1 any_key