#!/bin/bash
echo "****************************************"
echo "Linux Lite Additional Programs Installer"
echo "****************************************"
echo ""
echo "This will install Pidgin, an Instant Messaging client for Linux"
echo "so you can still chat on MSN, Yahoo, Google Talk, AIM, IRC, ICQ and more."
echo "Once installed, Pidgin is located in Menu, Internet."
echo "This window will automatically close when the install has completed."
echo "Support is available from - http://www.pidgin.im/"
echo ""
echo "Please enter your password to continue..."
sudo apt-get install pidgin -y