#!/bin/bash
echo "****************************************"
echo "Linux Lite Additional Programs Installer"
echo "****************************************"
echo ""
echo "This will install the Restricted Extras package."
echo "Once installed, this will give you additional codec"
echo "support in multimedia, and some Microsoft fonts."
echo "This window will automatically close when the install has completed."
echo ""
echo "Please enter your password to continue..."
sudo apt-get install ubuntu-restricted-extras -y