#!/bin/bash
echo "****************************************"
echo "Linux Lite Additional Programs Installer"
echo "****************************************"
echo ""
echo "This will install Remmina Remote Desktop for Windows(RDP) and VNC Servers."
echo "Once installed, Remmina is located in Menu, Internet."
echo "This window will automatically close when the install has completed."
echo "Support is available from - http://remmina.sourceforge.net/"
echo ""
echo "Please enter your password to continue..."
sudo apt-get install remmina -y