#!/bin/bash
echo "*************************"
echo "Restarting Network Shares"
echo "*************************"
echo ""
echo "This will restart your network share services"
echo "to apply the new settings."
echo ""
echo "This window will automatically close when network share services have restarted."
echo "Please enter your password to continue..."
sudo service smbd restart
sudo service nmbd restart
echo ""
echo "This window will now close."
sleep 3