#!/bin/bash

bold=`tput bold`
normal=`tput sgr0`

echo "**********************"
echo "Linux Lite Samba Setup"
echo "**********************"
echo ""
echo "This process will set up network shares"
echo "between this computer and a Windows computer."
echo "A Text Editor will open where you can edit a"
echo "configuration file. Please click on the Help & Support"
echo "Manual in the Menu and go to the Network link for further"
echo "instructions."
echo "After you have finished editing this file, you must"
echo "click on ${bold}Restart Network Share Services${normal} to apply the"
echo "new settings."
echo ""
echo "This window will automatically close when you save the text file."
echo "Please enter your password to continue..."
sudo leafpad /etc/samba/smb.conf