#!/bin/bash
echo "****************************************"
echo "Linux Lite Additional Programs Installer"
echo "****************************************"
echo ""
echo "This will install Catfish, simple to use file and folder searcher."
echo "Once installed, Catfish is located in Menu, Accessories."
echo "This window will automatically close when the install has completed."
echo "Support is available from - http://twotoasts.de/index.php/catfish/"
echo ""
echo "Please enter your password to continue..."
sudo apt-get install catfish -y