#!/bin/bash
echo "****************************************"
echo "Linux Lite Additional Programs Installer"
echo "****************************************"
echo ""
echo "This will install Galculator, a basic calculator with scientific functions."
echo "Once installed, Galculator is located in Menu, Accessories."
echo "This window will automatically close when the install has completed."
echo ""
echo "Please enter your password to continue..."
sudo apt-get install galculator -y