#!/bin/bash
echo "****************************************"
echo "Linux Lite Additional Programs Installer"
echo "****************************************"
echo ""
echo "This will install the Deluge Torrent client."
echo "Once installed, Deluge is located in Menu, Internet."
echo "This window will automatically close when the install has completed."
echo "Support is available from - http://deluge-torrent.org/"
echo ""
echo "Please enter your password to continue..."
sudo apt-get install deluge -y