#!/bin/bash

bold=`tput bold`
normal=`tput sgr0`

echo "${bold}****************************************"
echo "Linux Lite Additional Programs Installer"
echo "****************************************${normal}"
echo ""
echo "This will install the Deluge Torrent client."
echo "Once installed, ${bold}Deluge${normal} is located in ${bold}Menu, Internet.${normal}"
echo "This window will automatically close when the install has completed."
echo "Support is available from - http://deluge-torrent.org/"
echo ""
echo "Please enter your password to continue..."
sudo apt-get install deluge -y