#!/bin/bash
echo "****************************************"
echo "Linux Lite Additional Programs Installer"
echo "****************************************"
echo ""
echo "This will install the Openshot Video Editor."
echo "Once installed, Openshot is located in Menu, Multimedia."
echo "This window will automatically close when the install has completed."
echo "Support is available from - http://www.openshotvideo.com/"
echo ""
echo "Please enter your password to continue..."
sudo apt-get install openshot blender libavformat-extra-53 -y