#!/bin/bash

bold=`tput bold`
normal=`tput sgr0`

echo "${bold}****************************************"
echo "Linux Lite Additional Programs Installer"
echo "****************************************${normal}"
echo ""
echo "This will install the Openshot Video Editor."
echo "Once installed, ${bold}Openshot${normal} is located in ${bold}Menu, Multimedia.${normal}"
echo "This window will automatically close when the install has completed."
echo "Support is available from - http://www.openshotvideo.com/"
echo ""
echo "Please enter your password to continue..."
sudo apt-get install openshot blender libavformat-extra-53 -y