#!/bin/bash

bold=`tput bold`
normal=`tput sgr0`

echo "${bold}****************************************"
echo "Linux Lite Additional Programs Installer"
echo "****************************************${normal}"
echo ""
echo "This will install VirtualBox."
echo "VirtualBox allows you to try different Operating Systems"
echo "in a virtual environment."
echo "Once installed, ${bold}VirtualBox${normal} is located in ${bold}Menu, System.${normal}"
echo "This window will automatically close when the install has completed."
echo "Support is available from - https://www.virtualbox.org/"
echo ""
echo "Please enter your password to continue..."
sudo apt-get install virtualbox -y